version: '3.8'

services:
  api:
    image: localhost:5000/docker_api:${RELEASE_TAG}
    hostname: api
    container_name: api
    restart: always
    environment:
      DB_URI: ${DB_URI}
      APP_PORT: ${APP_PORT}
      JWT_SECRET: ${JWT_SECRET}
      BASE_URL: ${BASE_URL}
      PASS_EMAIL: ${PASS_EMAIL}
    ports:
      - 3005:3005
    expose:
      - "3005"

    networks:
      - default

  app:
    image: localhost:5000/docker_app:${RELEASE_TAG}
    hostname: app
    container_name: app
    restart: always
    depends_on:
      - api
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    ports:
      - 80:3009
    expose:
      - "80"
    networks:
      - default
networks:
  default:
    ipam:
      config:
        - subnet: ${DOCKER_DEFAULT_SUBNET}/24
    driver_opts:
      com.docker.network.driver.mtu: ${DOCKER_MTU:-1400}
